@echo off
echo Starting AI Blog Admin Portal...
cd /d "d:\ai-blog-website"
echo Opening admin portal in browser...
start http://localhost:3001/admin
echo Starting development server...
npm run dev
pause
