name: Deploy AI Blog

on:
  push:
    branches: [ main ]
  schedule:
    # Run daily at 9 AM UTC to generate new content
    - cron: '1 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate new blog post (if scheduled)
        if: github.event_name == 'schedule'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npm run generate-post
          
      - name: Commit and push new content (if any)
        if: github.event_name == 'schedule'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/content/
          if ! git diff --staged --quiet; then
            git commit -m "Add new AI-generated blog post [skip ci]"
            git push
          fi
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build Next.js app
        env:
          SITE_URL: https://aatish-ranjan.github.io/automated-ai-blog
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npm run generate-rss
          npm run build
          
      - name: Generate sitemap
        run: npx next-sitemap
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
